#ifndef GLOBALCONSTANT_H
#define GLOBALCONSTANT_H

int const MAX_LIMIT_OF_PLAYER = 50;

int const NO_OF_MSG_IN_QUEUE = 3000;
int const MAX_MSG_SIZE = 8000;
int const MAX_SENT_MSG_DATA_SIZE = 2000;

#define DISPLAY 1
#define SERVER 2



#define USER_ALREADY_EXIST 1
#define USER_SUCCESSFUL_SIGNUP 2
#define USER_SUCCESSFUL_LOGIN 3
#define USER_NOT_FOUND 4
#define INVALID_CREDENTIAL 5
#define CONTINUE_GAME 6
#define PLAYER_LIMIT_EXCEED 7
#define PLAYER_COUNT 8
#define START_THE_GAME 9



#define GAME_MODE_SOLO 1
#define GAME_MODE_DOMINATION 2

#endif // GLOBALCONSTANT_H
